entities:
  tags:
    title: Tag
    description: Allure test tags
    schema:
      $defs:

        tags.aspects.item:
          title: Aspect
          $ref: "#/$rels/aspects.aspect"

        tags.aspects:
          title: Aspects
          type: array
          minItems: 1
          items:
            $ref: "#/$defs/tags.aspects.item"

        tags:
          type: object
          properties:
            name:
              type: string
              title: Name
            aspects:
              title: Aspects
              $ref: "#/$defs/tags.aspects"
            id:
              type: integer
              title: ID
          required:
            - name
            - aspects


      type: object
      patternProperties:
        "^[a-zA-Z][a-zA-Z0-9_-]*(\\.[a-zA-Z0-9][a-zA-Z0-9_-]*)*$":
          $ref: "#/$defs/tags"
    objects:
      tag:
        route: "/"
        title: Tags

  ttags:
    title: Test tags
    objects:
      tag:
        route: "/"
        title: Tag
    schema:
      type: object
      patternProperties:
        "^[a-z0-9_\\$][a-z0-9_\\$]*(\\.[a-z0-9_\\$][a-z0-9_\\$]*)*$":
          type: object
          properties:
            name:
              title: Tag name
              type: string
          required:
            - name






