# Требования прикладной архитектуры SEAF
entities:
  seaf.change.requirements:
    menu: >
      (
        $append(
          [{
            "link": "/entities/seaf.change.requirements/tree", 
            "location": "Changes/Requirements" 
          }],
          $seaf_menu_location_by_id(
              $."seaf.change.requirements",
              "",
              "Changes/Requirements/",
              function($location, $item, $itemId, $collection){{
                  "location": $location,
                  "link": "/entities/seaf.change.requirements/blank?seaf-req-id=" & $itemId
              }}
          )
        );
      )